name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Formatter check
        run: deno fmt --config deno.json --check
      - name: Lint
        run: deno lint --config deno.json
      - name: Run tests
        run: deno test --allow-read=./fixtures
